In [1]:
import numpy as np

In [3]:
data=np.loadtxt(r"C:\Users\rs960\Downloads\even_numbers.txt")

In [4]:
print(data)

[[ 2.  4.  6.  8. 10.]
 [12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]
 [32. 34. 36. 38. 40.]
 [42. 44. 46. 48. 50.]]


In [7]:
data=np.loadtxt(r"C:\Users\rs960\Downloads\even_numbers.txt",dtype=int,skiprows=1,usecols=(1,3))
print(data)

[[14 18]
 [24 28]
 [34 38]
 [44 48]]


In [10]:
data=np.loadtxt(r"C:\Users\rs960\Downloads\glass.csv",delimiter=',')
print(data)
print(data.shape)
print(data.dtype)

[[  1.        1.52101  13.64    ...   0.        0.        1.     ]
 [  2.        1.51761  13.89    ...   0.        0.        1.     ]
 [  3.        1.51618  13.53    ...   0.        0.        1.     ]
 ...
 [212.        1.52065  14.36    ...   1.64      0.        7.     ]
 [213.        1.51651  14.38    ...   1.57      0.        7.     ]
 [214.        1.51711  14.23    ...   1.67      0.        7.     ]]
(214, 11)
float64


In [12]:
#data cleaning 
data=np.genfromtxt(r"C:\Users\rs960\Downloads\odd_numbers.csv",delimiter=',',missing_values='?',filling_values=0)
print(data)

[[ 1.  3.  5.  7.  9.]
 [11. 13. 15. 17. 19.]
 [21. 23. 25. 27. 29.]
 [31. 33. 35. 37. 39.]
 [43. 45. 47. 49.  0.]]


In [14]:
#array slicing 
print(data[:,1:])

[[ 3.  5.  7.  9.]
 [13. 15. 17. 19.]
 [23. 25. 27. 29.]
 [33. 35. 37. 39.]
 [45. 47. 49.  0.]]


In [15]:
print(data[0:2,1:4])

[[ 3.  5.  7.]
 [13. 15. 17.]]


In [21]:
#array reshape 
data.reshape(5,5)

array([[ 1.,  3.,  5.,  7.,  9.],
       [11., 13., 15., 17., 19.],
       [21., 23., 25., 27., 29.],
       [31., 33., 35., 37., 39.],
       [43., 45., 47., 49.,  0.]])

In [22]:
#array masking 
mask=(data<=5)
mask

array([[ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True]])